PlantUML
@startuml
class Client {
    - mainUser: User
    + CreatePlaylist(name: string)
    + AddSongToPlaylist(playlistName: string, song: Song)
    + PlayPlaylist(playlistName: string)
    + ViewFriends()
    + AddFriend(friend: User)
    + RemoveFriend(friend: User)
    + ViewFriendPlaylists(friend: User)
    + ViewAlbums()
    + ViewArtists()
}

class User {
    - name: string
    - playlists: List<Playlist>
    - friends: List<User>
    + CreatePlaylist(name: string)
    + AddSongToPlaylist(playlistName: string, song: Song)
    + PlayPlaylist(playlistName: string)
    + ViewFriends()
    + AddFriend(friend: User)
    + RemoveFriend(friend: User)
    + ViewFriendPlaylists(friend: User)
}

class Playlist {
    - name: string
    - songs: List<Song>
    + AddSong(song: Song)
    + RemoveSong(song: Song)
    + Play()
}

class Song {
    - title: string
    - artists: string[]
    - genre: string
    + Play()
    + Stop()
    + Skip()
}

class Album {
    - title: string
    - songs: List<Song>
    - artists: List<Artist>
    + Play()
}

class Artist {
    - name: string
    - albums: List<Album>
    - songs: List<Song>
    + ViewWorks()
}

Client --> User : mainUser
User --> Playlist : playlists
User --> User : friends
Playlist --> Song : songs
Album --> Song : songs
Album --> Artist : artists
Artist --> Album : albums
Artist --> Song : songs
@enduml